version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the application..."
      - npm run build

  post_build:
    commands:
      - echo "Uploading artifacts to S3..."
      - aws s3 cp ./dist s3://codebuild-testing-qa --recursive

artifacts:
  files:
    - '**/*'
